### PR TITLE
Getting started tutorial

### PR DESCRIPTION
**Pull request by appoose**
Adding the notebook  with the chat_with_video example that will be used for getting started video.

### CODE REVIEW

**Comment by appoose** [comment]
@movchan74  @ashwinnair14  @evanderiel  Can you review this tutorial I wrote for the getting started video?

**Review by evanderiel — APPROVED** [review]
LGTM

**Comment by movchan74** [comment]
>!pip install git+https://github.com/mobiusml/aana_sdk.git -qqqU

Shall we use pypi version instead?

**Comment by movchan74** [comment]
I would suggest to add a link to integrations https://github.com/mobiusml/aana_sdk/blob/main/docs/integrations.md when you talk about Deployments.

**Comment by movchan74** [comment]
```python
from aana.projects.chat_with_video.const import (
    asr_model_name,
    captioning_model_name,
    max_video_len,
)
from aana.projects.chat_with_video.utils import (
    generate_dialog,
)
```

consts and generate_dialog util function are coming from the chat_with_video project.

**Comment by appoose** [comment]
> ```python
> from aana.projects.chat_with_video.const import (
>     asr_model_name,
>     captioning_model_name,
>     max_video_len,
> )
> from aana.projects.chat_with_video.utils import (
>     generate_dialog,
> )
> ```
> 
> consts and generate_dialog util function are imported from the chat_with_video project.

I will take it into the main notebook body. 

Question: I find the models being defined at two places and potentially can cause issues. One in the .const and other in deploys configs 

```
asr_model_name = "whisper_medium"
captioning_model_name = "hf_blip2_opt_2_7b"
max_video_len = 60 * 20  # 20 minutes


deployments = [
    {
        "name": "asr_deployment",
        "instance": whisper_medium_deployment,
    },    
    {
        "name": "captioning_deployment",
        "instance": hf_blip2_opt_2_7b_deployment,
    },
    {
        "name": "llm_deployment",
        "instance": internlm2_5_7b_chat_deployment,
    },
]

for deployment in deployments:
    aana_app.register_deployment(
        name=deployment["name"],
        instance=deployment["instance"],
    )
```

What might be a better way of handling this?

**Comment by movchan74** [comment]
> > ```python
> > from aana.projects.chat_with_video.const import (
> >     asr_model_name,
> >     captioning_model_name,
> >     max_video_len,
> > )
> > from aana.projects.chat_with_video.utils import (
> >     generate_dialog,
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > consts and generate_dialog util function are imported from the chat_with_video project.
> 
> I will take it into the main notebook body.
> 
> Question: I find the models being defined at two places and potentially can cause issues. One in the .const and other in deploys configs
> 
> ```
> asr_model_name = "whisper_medium"
> captioning_model_name = "hf_blip2_opt_2_7b"
> max_video_len = 60 * 20  # 20 minutes
> 
> 
> deployments = [
>     {
>         "name": "asr_deployment",
>         "instance": whisper_medium_deployment,
>     },    
>     {
>         "name": "captioning_deployment",
>         "instance": hf_blip2_opt_2_7b_deployment,
>     },
>     {
>         "name": "llm_deployment",
>         "instance": internlm2_5_7b_chat_deployment,
>     },
> ]
> 
> for deployment in deployments:
>     aana_app.register_deployment(
>         name=deployment["name"],
>         instance=deployment["instance"],
>     )
> ```
> 
> What might be a better way of handling this?

Model names from const are only used for the database ops. Maybe we can call deployments and get the model name from it in the future.

**Comment by appoose** [comment]
Okay, then I will keep as it is and update when we have facility to call deployments and get models names.

**Review by movchan74 — APPROVED** [review]

**Pull request merged**
